### ISSUE TITLE
add saving players

### ISSUE THREAD

**Issue by moderator10000078** [Hetag1216/AreaReloader-FAWE#1]
I would like the plugin to have a function that, when loading a territory, would teleport players to a safe zone for them

**Comment by Hetag1216** [comment]
Hello, this would not be implemented in the plugin as its only purpose is to restore areas.
However, with future updates I will make sure to implement events so that third party plugins can act on them.
I already planned of making a "utility" dependency that will allow consumers to further customise the behaviour of things such as when an area is loaded and so on.
Thank you for the suggestion, if you'd have any other feel free to post them in here or on discord!

**Comment by Hetag1216** [comment]
Introduced teleportation mechanic [c499195](https://github.com/Hetag1216/AreaReloader-FAWE/commit/c4991957d9bd35c4d8d3688577050628d3d745d1).

**Comment by moderator10000078** [comment]
I am glad that after all this time my idea was not forgotten, I would also like to have an implementation that the plugin takes x and z of the player and teleports to the nearest safe y coordinate above the player (if the player under the threat of suffocation or burning in the lava), I would be very grateful for this

**Comment by Hetag1216** [comment]
Thank you in the first place for suggesting this mechanic!
If I understand correctly what you're furtherly suggesting refers, for instance, to players who're standing under an area that has been reloaded, but however, aren't inside the inbox of the area itself.
The teleportation mechanic can be quite heavy depending on the area's size and the amount of players to be teleported, hence I wouldn't make it so the check would happen for nearby coordinates adjacent to the area's bounds as that would make everything even heavier and resource intensive.
However, what could be done is to implement an adjustable radius for the teleportation itself, that for each coordinate doesn't analyse a single block but rather x blocks of configured radius!
