### ISSUE TITLE
commands after completing a reload of the territory

### ISSUE THREAD

**Issue by moderator10000078** [Hetag1216/AreaReloader-FAWE#3]
This setting would be useful when used with other plugins (like spavin boss or something else)

**Comment by Hetag1216** [comment]
I'm afraid I will not add this functionality within the plugin as the main purpose is that of restoring terrains, furthermore the plugin can sometimes be heavy depending on server's resources and I do my best to keep it as non-resource intensive as I can so that it may be accessible to everyone.
However, with the latest patches' additions, events have been added to support API usage for developers in order to allow customisation using 3rd party implementations.
However, as I said in the past, in the near future I will release a side plugin for AreaReloader that will introduce functionalities only for events in order to allow server owners to customise the plugin even beyond basic configuration!
